# Java 25 es la versión configurada en backend/pom.xml.
FROM eclipse-temurin:25-jdk AS build

# Instalar Node.js y npm necesarios para compilar React
RUN apt-get update && apt-get install -y nodejs npm

WORKDIR /app
COPY backend ./backend
COPY frontend ./frontend

# Dar permisos al wrapper de Maven
RUN chmod +x backend/mvnw

# Compilar backend y frontend
RUN cd backend && ./mvnw clean package -DskipTests

# Etapa de ejecución (ligera)
FROM eclipse-temurin:25-jre

WORKDIR /app
COPY --from=build /app/backend/target/backend-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]